[package]
name = "backend_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
aide = { version = "0.13.4", features = ["macros"] }
axum = "0.7.7"
axum-jsonschema = "0.8.0"
axum-macros = "0.4.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
