[package]
name = "backend_routes"
version = "0.1.0"
edition = "2021"

[dependencies]
aide = "0.13.4"
axum = { version =  "0.7.7", features = ["macros"] }

backend_models = { path = "../backend-models" }
